# Generated by Django 2.2 on 2021-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madlib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blankCount', models.IntegerField()),
                ('firstType', models.CharField(max_length=100)),
                ('secondType', models.CharField(max_length=100)),
                ('thirdType', models.CharField(max_length=100)),
                ('fourthType', models.CharField(max_length=100)),
                ('fifthType', models.CharField(max_length=100)),
                ('sixthType', models.CharField(max_length=100)),
                ('seventhType', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=1000)),
            ],
        ),
    ]
