# Generated by Django 2.2 on 2021-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlib',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
