# Generated by Django 2.2 on 2021-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlib', '0002_madlib_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madlib',
            old_name='firstType',
            new_name='type1',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='secondType',
            new_name='type2',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='thirdType',
            new_name='type3',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='fourthType',
            new_name='type4',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='fifthType',
            new_name='type5',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='sixthType',
            new_name='type6',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='seventhType',
            new_name='type7',
        ),
        migrations.AlterField(
            model_name='madlib',
            name='blankCount',
            field=models.IntegerField(default=7),
        ),
    ]
