# Generated by Django 2.2 on 2021-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlib', '0004_auto_20211025_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlib',
            name='type10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='madlib',
            name='type8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='madlib',
            name='type9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='type7',
            field=models.CharField(default='', max_length=100),
        ),
    ]
