# Generated by Django 2.2 on 2021-10-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madlib', '0005_auto_20211025_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlib',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part2',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part3',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part4',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part5',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part6',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part7',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='part8',
        ),
    ]
